FROM diegomarangoni/hhvm:cli

ARG COMPOSER_OPTS

RUN apt-get update && apt-get install -y curl wget graphviz

COPY . /app
WORKDIR /app

RUN /app/bin/install-composer.sh && composer update $COMPOSER_OPTS
