FROM alpine:edge

ARG COMPOSER_OPTS

RUN apk add --no-cache curl git graphviz php7 php7-json php7-phar php7-openssl php7-mbstring php7-dom php7-ctype php7-curl \
 && ln -s /usr/bin/php7 /usr/bin/php

COPY . /phpda
WORKDIR /phpda

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
 && composer update $COMPOSER_OPTS

CMD [""]
