version: '3.5'

services:
  php73: &services_php73
    build:
      context: .
      target: dev
      args:
        PHP_TAG: '7.3-cli-alpine3.14'
    environment:
      COMPOSER_HOME: /app/var/cache/composer
    working_dir: /phpda
    volumes:
      - .:/phpda
      - .:/app
    entrypoint:
      - sh
      - -c
      - |
        exec tail -f /dev/null

  release.php73:
    <<: *services_php73
    build:
      context: .
      target: prod
      args:
        PHP_TAG: '7.3-cli-alpine3.14'
        PHPDA_VERSION: ${PHPDA_VERSION-}

  php74:
    <<: *services_php73
    build:
      context: .
      target: dev
      args:
        PHP_TAG: '7.4-cli-alpine3.15'

  release.php74:
    <<: *services_php73
    build:
      context: .
      target: prod
      args:
        PHP_TAG: '7.4-cli-alpine3.15'
        PHPDA_VERSION: ${PHPDA_VERSION-}

  php80:
    <<: *services_php73
    build:
      context: .
      target: dev
      args:
        PHP_TAG: '8.0-cli-alpine3.16'

  release.php80:
    <<: *services_php73
    build:
      context: .
      target: prod
      args:
        PHP_TAG: '8.0-cli-alpine3.16'
        PHPDA_VERSION: ${PHPDA_VERSION-}
